name: Semantic PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    uses: somaz94/.github/.github/workflows/semantic-pr-reusable.yml@f985f57e4970eba23bdc913f91933813d7cab8fa # main
